spring:
  profiles:
    active: dev
    include:
    - oauth
  data:
    web:
      pageable:
        max-page-size: 50
        default-page-size: 20
        
logging:
  level:
    com.hjt: debug 
    org.hibernate.SQL: debug #logger를 통해 출력
    org.hibernate.type: trace #SQL 쿼리 파라미터를 확인할 수 있다
    org.spring.framework.web: debug 
    org.springframework.security: debug

---
spring:
  profiles:
  - test
  datasource:
    url: jdbc:h2:mem:spring-boot-aws
    
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100

---
spring:
  profiles:
  - dev
  datasource:
    url: jdbc:h2:tcp://localhost/~/spring-boot-aws
    
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100